kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: guestbook-ui
  namespace: guestbook
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: guestbook.gitops.local
      http:
        paths:
          - path: /
            backend:
              serviceName: guestbook-ui
              servicePort: 80